# Generated by Django 3.2 on 2022-10-16 18:39

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewards',
            name='activity',
        ),
        migrations.AlterField(
            model_name='rewards',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='campaigninvolvement',
            unique_together={('user', 'campaign')},
        ),
        migrations.CreateModel(
            name='TreeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
