# Generated by Django 3.2 on 2022-10-21 09:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221016_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclearea',
            name='waste_type',
            field=models.CharField(choices=[('P', 'Plastics'), ('A', 'All')], default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='RecycleCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('comments', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recyclearea')),
            ],
        ),
    ]
