# Generated by Django 3.2 on 2022-10-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_recyclecall_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='price',
            field=models.FloatField(default=100),
        ),
    ]
