# Generated by Django 3.2 on 2022-10-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tree_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='category',
            field=models.CharField(choices=[('H', 'Hardwood'), ('S', 'Softwood')], default='S', max_length=2),
        ),
    ]
